# Site Settings
title: Seyyad Najwan
description: "Portfolio of Seyyad Najwan - Web Developer & Designer"
baseurl: ""
url: "https://yourdomain.com"  

# Theme & Appearance
theme: jekyll-theme-minimal
show_downloads: false  # Disable if not needed
permalink: pretty

# Author Details
author:
  name: Seyyad Najwan
  email: mohamednajwan97@email.com
  bio: "Data Analyst"
  social:
    github: StatisticsOR
    twitter: yourhandle
    linkedin: yourprofile

# Navigation
nav_links:
  - name: Home
    url: /
  - name: About
    url: /about
  - name: Projects
    url: /#projects

# Customization
plugins:
  - jekyll-seo-tag
